export const USER_LOGIN_FETCHING = 'LOGIN_FETCHING'
export const USER_LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'LOGIN_ERROR'

export const THREADS_LISTING_FETCHING = 'FETCHING'
export const THREADS_LISTING_FETCH_SUCCESS = 'FETCH_SUCCESS'
export const THREADS_LISTING_FETCH_ERROR = 'FETCH_ERROR'
